name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    runs-on: ubuntu-latest # Cambia a latest para asegurar recursos frescos
    steps:
      - uses: actions/checkout@v4
      
      # Paso para asegurar espacio en el disco antes del escaneo
      - name: Limpiar espacio temporal
        run: |
          sudo rm -rf /tmp/*
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
